### ISSUE TITLE
Current weather

### ISSUE THREAD

**Issue by leovannieiwenborg** [AdyRock/com.weatherunderground#12]
I want to make a flow when the wind changes and is stronger then 10 kn/h close the sun screen.

What I mis to add the current wind speed/burst from my weather station. I only can add values from the weather forecast part of the app.

Is there anything  I do not see?

**Comment by AdyRock** [comment]
I think you mean you don't see options for the And cards?
If so then you can use the Logic card to compare a tag and select the Wind Strength or Gust tag.
If you have a When card of Gust has changed, etc,  then it provides a local tag but all the current weather parameters are available as global tags.

I added the specific conditions for the forecast because you need to specify the day but the current weather data only has now.

Hope that makes sense.
